config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :jobtitles
  resources :magazines
  resources :oenologists
  resources :winestrains
  resources :strains
  resources :wines

  root "wines#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/magazine.rb
class Magazine < ApplicationRecord
  has_many :magazineoenologistjobtitles
  has_many :oenologists, through: :magazineoenologistjobtitles
  has_many :jobtitles, through: :magazineoenologistjobtitles
end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController
  before_action :set_magazine, only: [:show, :edit, :update, :destroy]

  # GET /magazines
  # GET /magazines.json
  def index
    @magazines = Magazine.all
  end

  # GET /magazines/1
  # GET /magazines/1.json
  def show
  end

  # GET /magazines/new
  def new
    @magazine = Magazine.new
  end

  # GET /magazines/1/edit
  def edit
  end

  # POST /magazines
  # POST /magazines.json
  def create
    @magazine = Magazine.new(magazine_params)

    respond_to do |format|
      if @magazine.save
        format.html { redirect_to @magazine, notice: 'Magazine was successfully created.' }
        format.json { render :show, status: :created, location: @magazine }
      else
        format.html { render :new }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /magazines/1
  # PATCH/PUT /magazines/1.json
  def update
    respond_to do |format|
      if @magazine.update(magazine_params)
        format.html { redirect_to @magazine, notice: 'Magazine was successfully updated.' }
        format.json { render :show, status: :ok, location: @magazine }
      else
        format.html { render :edit }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /magazines/1
  # DELETE /magazines/1.json
  def destroy
    @magazine.destroy
    respond_to do |format|
      format.html { redirect_to magazines_url, notice: 'Magazine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_magazine
      @magazine = Magazine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def magazine_params
      params.require(:magazine).permit(:name)
    end
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/views/magazines/_form.html.erb
<%= form_with(model: magazine, local: true) do |form| %>
  <% if magazine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(magazine.errors.count, "error") %> prohibited this magazine from being saved:</h2>

      <ul>
      <% magazine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/magazines/edit.html.erb
<h1>Editing Magazine</h1>

<%= render 'form', magazine: @magazine %>

<%= link_to 'Show', @magazine %> |
<%= link_to 'Back', magazines_path %>

app/views/magazines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Magazines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @magazines.each do |magazine| %>
      <tr>
        <td><%= magazine.name %></td>
        <td><%= link_to 'Show', magazine %></td>
        <td><%= link_to 'Edit', edit_magazine_path(magazine) %></td>
        <td><%= link_to 'Destroy', magazine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Magazine', new_magazine_path %>

app/views/magazines/new.html.erb
<h1>New Magazine</h1>

<%= render 'form', magazine: @magazine %>

<%= link_to 'Back', magazines_path %>

app/views/magazines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @magazine.name %>
</p>

<%= link_to 'Edit', edit_magazine_path(@magazine) %> |
<%= link_to 'Back', magazines_path %>