config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :jobtitles
  resources :magazines
  resources :oenologists
  resources :winestrains
  resources :strains
  resources :wines

  root "wines#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/winestrain.rb
class Winestrain < ApplicationRecord
  belongs_to :wine
  belongs_to :strain
end

app/controllers/winestrains_controller.rb
class WinestrainsController < ApplicationController
  before_action :set_winestrain, only: [:show, :edit, :update, :destroy]
  

  # GET /winestrains
  # GET /winestrains.json
  def index
    @winestrains = Winestrain.all
  end

  # GET /winestrains/1
  # GET /winestrains/1.json
  def show
  end

  # GET /winestrains/new
  def new
    @winestrain = Winestrain.new
  end

  # GET /winestrains/1/edit
  def edit
  end

  # POST /winestrains
  # POST /winestrains.json
  def create
    @winestrain = Winestrain.new(winestrain_params)

    respond_to do |format|
      if @winestrain.save
        format.html { redirect_to @winestrain, notice: 'Winestrain was successfully created.' }
        format.json { render :show, status: :created, location: @winestrain }
      else
        format.html { render :new }
        format.json { render json: @winestrain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /winestrains/1
  # PATCH/PUT /winestrains/1.json
  def update
    respond_to do |format|
      if @winestrain.update(winestrain_params)
        format.html { redirect_to @winestrain, notice: 'Winestrain was successfully updated.' }
        format.json { render :show, status: :ok, location: @winestrain }
      else
        format.html { render :edit }
        format.json { render json: @winestrain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /winestrains/1
  # DELETE /winestrains/1.json
  def destroy
    @winestrain.destroy
    respond_to do |format|
      format.html { redirect_to winestrains_url, notice: 'Winestrain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_winestrain
      @winestrain = Winestrain.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def winestrain_params
      params.require(:winestrain).permit(:wine_id, :strain_id, :percentage)
    end
end

app/helpers/winestrains_helper.rb
module WinestrainsHelper
end

app/views/winestrains/_form.html.erb
<%= form_with(model: winestrain, local: true) do |form| %>
  <% if winestrain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(winestrain.errors.count, "error") %> prohibited this winestrain from being saved:</h2>

      <ul>
      <% winestrain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :wine_id %>
    <%= form.text_field :wine_id %>
  </div>

  <div class="field">
    <%= form.label :strain_id %>
    <%= form.text_field :strain_id %>
  </div>

  <div class="field">
    <%= form.label :percentage %>
    <%= form.number_field :percentage %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/winestrains/edit.html.erb
<h1>Editing Winestrain</h1>

<%= render 'form', winestrain: @winestrain %>

<%= link_to 'Show', @winestrain %> |
<%= link_to 'Back', winestrains_path %>

app/views/winestrains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Winestrains</h1>

<table>
  <thead>
    <tr>
      <th>Wine</th>
      <th>Strain</th>
      <th>Percentage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @winestrains.each do |winestrain| %>
      <tr>
        <td><%= winestrain.wine %></td>
        <td><%= winestrain.strain %></td>
        <td><%= winestrain.percentage %></td>
        <td><%= link_to 'Show', winestrain %></td>
        <td><%= link_to 'Edit', edit_winestrain_path(winestrain) %></td>
        <td><%= link_to 'Destroy', winestrain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Winestrain', new_winestrain_path %>

app/views/winestrains/new.html.erb
<h1>New Winestrain</h1>

<%= render 'form', winestrain: @winestrain %>

<%= link_to 'Back', winestrains_path %>

app/views/winestrains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wine:</strong>
  <%= @winestrain.wine %>
</p>

<p>
  <strong>Strain:</strong>
  <%= @winestrain.strain %>
</p>

<p>
  <strong>Percentage:</strong>
  <%= @winestrain.percentage %>
</p>

<%= link_to 'Edit', edit_winestrain_path(@winestrain) %> |
<%= link_to 'Back', winestrains_path %>